name: Android CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Rename Debug APK
        id: rename_apk
        run: |
          SHORT_HASH=$(git rev-parse --short HEAD)
          NEW_NAME="de.meonwax.soundboard-${SHORT_HASH}.apk"
          mv app/build/outputs/apk/debug/app-debug.apk "${NEW_NAME}"
          echo "apk_name=${NEW_NAME}" >> $GITHUB_OUTPUT

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.rename_apk.outputs.apk_name }}
          path: ${{ steps.rename_apk.outputs.apk_name }}

  publish:
    needs: build
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'release' && github.event.action == 'created')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Keystore
        env:
          SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          echo $SIGNING_KEY_STORE_BASE64 > keystore.jks.base64
          base64 -d keystore.jks.base64 > app/keystore.jks

      - name: Build signed APK
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease \
            -PreleaseKeyStore=keystore.jks \
            -PreleaseKeyStorePassword=$SIGNING_STORE_PASSWORD \
            -PreleaseKeyAlias=$SIGNING_KEY_ALIAS \
            -PreleaseKeyAliasPassword=$SIGNING_KEY_PASSWORD

      - name: Get Release Upload URL
        id: get_upload_url
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "upload_url=${{ github.event.release.upload_url }}" >> $GITHUB_OUTPUT
          else
            echo "upload_url=$(jq --raw-output .upload_url "$GITHUB_EVENT_PATH")" >> $GITHUB_OUTPUT
          fi

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release.apk
          asset_name: de.meonwax.soundboard-${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive
